In [31]:
import pandas as pd

# read csv file 

df = pd.read_csv('hydroponics_data.csv')
df

,id,timestamp,pH,TDS,water_level,DHT_temp,DHT_humidity,water_temp,pH_reducer,add_water,nutrients_adder,humidifier,ex_fan
0,1,2023-11-26 10:57:52,7.00,500.00,0,25.5,60.0,20.00,ON,NaN,OFF,OFF,ON
1,2,2023-11-26 10:58:37,7.00,500.00,0,25.5,60.0,20.00,ON,NaN,OFF,OFF,OFF
2,3,2023-11-26 11:01:34,7.00,500.00,3,25.5,60.0,20.00,ON,NaN,OFF,OFF,OFF
3,4,2023-12-05 11:30:58,7.00,500.00,3,25.5,60.0,20.00,ON,NaN,OFF,OFF,OFF
4,5,2023-12-05 11:33:50,7.00,500.00,3,25.5,60.0,20.00,ON,ON,OFF,OFF,OFF
...,...,...,...,...,...,...,...,...,...,...,...,...,...
50565,50566,2023-12-26 21:34:40,5.54,1125.10,1,23.9,77.7,21.82,OFF,OFF,OFF,OFF,OFF
50566,50567,2023-12-26 21:34:50,5.55,1125.10,1,23.9,77.7,19.83,OFF,OFF,OFF,OFF,OFF
50567,50568,2023-12-26 21:35:00,5.57,1125.21,1,23.9,77.7,19.41,OFF,OFF,OFF,OFF,OFF
50568,50569,2023-12-26 21:35:10,5.56,1124.89,1,23.9,77.7,19.88,OFF,OFF,OFF,OFF,OFF
50569,50570,2023-12-26 21:36:40,5.55,1125.10,1,23.9,77.7,24.61,OFF,OFF,OFF,OFF,OFF

In [40]:
df.index.is_monotonic_increasing

True

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50570 entries, 0 to 50569
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               50570 non-null  int64
 1   timestamp        50570 non-null  str
 2   pH               50570 non-null  float64
 3   TDS              50570 non-null  float64
 4   water_level      50570 non-null  int64
 5   DHT_temp         50570 non-null  float64
 6   DHT_humidity     50570 non-null  float64
 7   water_temp       50570 non-null  float64
 8   pH_reducer       50570 non-null  str
 9   add_water        50566 non-null  str
 10  nutrients_adder  50570 non-null  str
 11  humidifier       50570 non-null  str
 12  ex_fan           50570 non-null  str
dtypes: float64(5), int64(2), str(6)
memory usage: 5.0 MB

In [8]:
df.describe()

,id,pH,TDS,water_level,DHT_temp,DHT_humidity,water_temp
count,50570.000000,50570.000000,50570.000000,50570.000000,50570.000000,50570.000000,50570.000000
mean,25285.500000,6.001514,1154.134377,1.258829,24.316781,71.714188,21.494904
std,14598.445893,0.553016,247.507196,0.479218,1.209319,25.956493,2.174898
min,1.000000,0.270000,-283.910000,0.000000,12.300000,25.000000,0.000000
25%,12643.250000,5.630000,1020.040000,1.000000,23.600000,67.500000,19.770000
50%,25285.500000,5.790000,1234.650000,1.000000,24.400000,71.700000,21.520000
75%,37927.750000,6.680000,1329.067500,2.000000,25.100000,77.500000,23.277500
max,50570.000000,11.570000,2278.350000,3.000000,70.000000,3312.600000,25.000000

In [9]:
# check missing value

df.isnull().sum()

id                 0
timestamp          0
pH                 0
TDS                0
water_level        0
DHT_temp           0
DHT_humidity       0
water_temp         0
pH_reducer         0
add_water          4
nutrients_adder    0
humidifier         0
ex_fan             0
dtype: int64

In [10]:
# check same rows 

df.duplicated().sum()

np.int64(0)

In [25]:
df.dtypes

id                   int64
pH                 float64
TDS                float64
water_level          int64
DHT_temp           float64
DHT_humidity       float64
water_temp         float64
pH_reducer             str
add_water              str
nutrients_adder        str
humidifier             str
ex_fan                 str
dtype: object

In [26]:
df.index

RangeIndex(start=0, stop=50570, step=1)

In [27]:
df = df.sort_index()
df

,id,pH,TDS,water_level,DHT_temp,DHT_humidity,water_temp,pH_reducer,add_water,nutrients_adder,humidifier,ex_fan
0,1,7.00,500.00,0,25.5,60.0,20.00,ON,NaN,OFF,OFF,ON
1,2,7.00,500.00,0,25.5,60.0,20.00,ON,NaN,OFF,OFF,OFF
2,3,7.00,500.00,3,25.5,60.0,20.00,ON,NaN,OFF,OFF,OFF
3,4,7.00,500.00,3,25.5,60.0,20.00,ON,NaN,OFF,OFF,OFF
4,5,7.00,500.00,3,25.5,60.0,20.00,ON,ON,OFF,OFF,OFF
...,...,...,...,...,...,...,...,...,...,...,...,...
50565,50566,5.54,1125.10,1,23.9,77.7,21.82,OFF,OFF,OFF,OFF,OFF
50566,50567,5.55,1125.10,1,23.9,77.7,19.83,OFF,OFF,OFF,OFF,OFF
50567,50568,5.57,1125.21,1,23.9,77.7,19.41,OFF,OFF,OFF,OFF,OFF
50568,50569,5.56,1124.89,1,23.9,77.7,19.88,OFF,OFF,OFF,OFF,OFF
50569,50570,5.55,1125.10,1,23.9,77.7,24.61,OFF,OFF,OFF,OFF,OFF

In [28]:
df = df.reset_index()  # timestamp กลับมาเป็น column
df = df.sort_values('timestamp')
df

KeyError: 'timestamp'

In [ ]:
df = df.reset_index()
print(df.columns.tolist())  # ดูว่า column ชื่ออะไร

['level_0', 'index', 'id', 'pH', 'TDS', 'water_level', 'DHT_temp', 'DHT_humidity', 'water_temp', 'pH_reducer', 'add_water', 'nutrients_adder', 'humidifier', 'ex_fan']

In [30]:
df = pd.read_csv('hydroponics_data.csv')
df['timestamp'] = pd.to_datetime(df['timestamp'])
df = df.sort_values('timestamp').reset_index(drop=True)
df

,id,timestamp,pH,TDS,water_level,DHT_temp,DHT_humidity,water_temp,pH_reducer,add_water,nutrients_adder,humidifier,ex_fan
0,1,2023-11-26 10:57:52,7.00,500.00,0,25.5,60.0,20.00,ON,NaN,OFF,OFF,ON
1,2,2023-11-26 10:58:37,7.00,500.00,0,25.5,60.0,20.00,ON,NaN,OFF,OFF,OFF
2,3,2023-11-26 11:01:34,7.00,500.00,3,25.5,60.0,20.00,ON,NaN,OFF,OFF,OFF
3,4,2023-12-05 11:30:58,7.00,500.00,3,25.5,60.0,20.00,ON,NaN,OFF,OFF,OFF
4,5,2023-12-05 11:33:50,7.00,500.00,3,25.5,60.0,20.00,ON,ON,OFF,OFF,OFF
...,...,...,...,...,...,...,...,...,...,...,...,...,...
50565,50566,2023-12-26 21:34:40,5.54,1125.10,1,23.9,77.7,21.82,OFF,OFF,OFF,OFF,OFF
50566,50567,2023-12-26 21:34:50,5.55,1125.10,1,23.9,77.7,19.83,OFF,OFF,OFF,OFF,OFF
50567,50568,2023-12-26 21:35:00,5.57,1125.21,1,23.9,77.7,19.41,OFF,OFF,OFF,OFF,OFF
50568,50569,2023-12-26 21:35:10,5.56,1124.89,1,23.9,77.7,19.88,OFF,OFF,OFF,OFF,OFF
50569,50570,2023-12-26 21:36:40,5.55,1125.10,1,23.9,77.7,24.61,OFF,OFF,OFF,OFF,OFF

In [32]:
df = df.reset_index()
print(df.columns.tolist())  # ดูว่า column ชื่ออะไร

['index', 'id', 'timestamp', 'pH', 'TDS', 'water_level', 'DHT_temp', 'DHT_humidity', 'water_temp', 'pH_reducer', 'add_water', 'nutrients_adder', 'humidifier', 'ex_fan']

In [33]:
df = df.sort_values('timestamp').reset_index(drop=True)
df

,index,id,timestamp,pH,TDS,water_level,DHT_temp,DHT_humidity,water_temp,pH_reducer,add_water,nutrients_adder,humidifier,ex_fan
0,0,1,2023-11-26 10:57:52,7.00,500.00,0,25.5,60.0,20.00,ON,NaN,OFF,OFF,ON
1,1,2,2023-11-26 10:58:37,7.00,500.00,0,25.5,60.0,20.00,ON,NaN,OFF,OFF,OFF
2,2,3,2023-11-26 11:01:34,7.00,500.00,3,25.5,60.0,20.00,ON,NaN,OFF,OFF,OFF
3,3,4,2023-12-05 11:30:58,7.00,500.00,3,25.5,60.0,20.00,ON,NaN,OFF,OFF,OFF
4,4,5,2023-12-05 11:33:50,7.00,500.00,3,25.5,60.0,20.00,ON,ON,OFF,OFF,OFF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50565,50565,50566,2023-12-26 21:34:40,5.54,1125.10,1,23.9,77.7,21.82,OFF,OFF,OFF,OFF,OFF
50566,50566,50567,2023-12-26 21:34:50,5.55,1125.10,1,23.9,77.7,19.83,OFF,OFF,OFF,OFF,OFF
50567,50567,50568,2023-12-26 21:35:00,5.57,1125.21,1,23.9,77.7,19.41,OFF,OFF,OFF,OFF,OFF
50568,50568,50569,2023-12-26 21:35:10,5.56,1124.89,1,23.9,77.7,19.88,OFF,OFF,OFF,OFF,OFF
50569,50569,50570,2023-12-26 21:36:40,5.55,1125.10,1,23.9,77.7,24.61,OFF,OFF,OFF,OFF,OFF

In [34]:
df = df.set_index("timestamp")

In [35]:
df.index.is_monotonic_increasing

True

In [38]:
print(df.columns.tolist())
print(df.index.name)

['index', 'id', 'pH', 'TDS', 'water_level', 'DHT_temp', 'DHT_humidity', 'water_temp', 'pH_reducer', 'add_water', 'nutrients_adder', 'humidifier', 'ex_fan']
timestamp

In [39]:
# ไม่ต้อง set_index แล้ว
numeric_cols = ['pH', 'TDS', 'water_level', 'DHT_temp', 'DHT_humidity', 'water_temp']
categorical_cols = ['pH_reducer', 'add_water', 'nutrients_adder', 'humidifier', 'ex_fan']

df_numeric = df[numeric_cols].resample('5min').mean().round(3)
df_cat = df[categorical_cols].resample('5min').last()

df_resampled = pd.concat([df_numeric, df_cat], axis=1).reset_index()
df_resampled

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'

In [ ]:
# choose 3 important columns

# df_subset = df[['id','timestamp','pH', 'TDS', 'water_temp']]

# df_subset.head()

# df_subset.to_csv('hydro_clean_data.csv', index=False)

   id            timestamp   pH    TDS  water_temp
0   1  2023-11-26 10:57:52  7.0  500.0        20.0
1   2  2023-11-26 10:58:37  7.0  500.0        20.0
2   3  2023-11-26 11:01:34  7.0  500.0        20.0
3   4  2023-12-05 11:30:58  7.0  500.0        20.0
4   5  2023-12-05 11:33:50  7.0  500.0        20.0

In [41]:
import pandas as pd

df = pd.read_csv('hydroponics_data.csv')
df['timestamp'] = pd.to_datetime(df['timestamp'])
df = df.set_index('timestamp').sort_index()

In [42]:
numeric_cols = ['pH', 'TDS', 'water_level', 'DHT_temp', 'DHT_humidity', 'water_temp']
categorical_cols = ['pH_reducer', 'add_water', 'nutrients_adder', 'humidifier', 'ex_fan']

In [43]:
df_numeric = df[numeric_cols].resample('5min').mean().round(3)
df_cat = df[categorical_cols].resample('5min').last()

In [44]:
df_resampled = pd.concat([df_numeric, df_cat], axis=1).reset_index()
df_resampled

,timestamp,pH,TDS,water_level,DHT_temp,DHT_humidity,water_temp,pH_reducer,add_water,nutrients_adder,humidifier,ex_fan
0,2023-11-26 10:55:00,7.000,500.000,0.0,25.500,60.000,20.000,ON,NaN,OFF,OFF,OFF
1,2023-11-26 11:00:00,7.000,500.000,3.0,25.500,60.000,20.000,ON,NaN,OFF,OFF,OFF
2,2023-11-26 11:05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-11-26 11:10:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-11-26 11:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
8764,2023-12-26 21:15:00,5.588,1125.941,1.0,23.977,77.623,21.496,OFF,OFF,OFF,OFF,OFF
8765,2023-12-26 21:20:00,5.587,1125.808,1.0,23.817,77.477,21.118,OFF,OFF,OFF,OFF,OFF
8766,2023-12-26 21:25:00,5.595,1125.510,1.0,23.917,77.607,21.300,OFF,OFF,OFF,OFF,OFF
8767,2023-12-26 21:30:00,5.591,1125.316,1.0,23.903,77.657,21.482,OFF,OFF,OFF,OFF,OFF
8768,2023-12-26 21:35:00,5.560,1125.067,1.0,23.900,77.700,21.300,OFF,OFF,OFF,OFF,OFF

In [45]:
df_resampled.isna().sum()

timestamp             0
pH                 7394
TDS                7394
water_level        7394
DHT_temp           7394
DHT_humidity       7394
water_temp         7394
pH_reducer         7394
add_water          7396
nutrients_adder    7394
humidifier         7394
ex_fan             7394
dtype: int64

In [46]:
df_resampled = df_resampled.dropna(how="all")

In [47]:
df_resampled.isna().sum()

timestamp             0
pH                 7394
TDS                7394
water_level        7394
DHT_temp           7394
DHT_humidity       7394
water_temp         7394
pH_reducer         7394
add_water          7396
nutrients_adder    7394
humidifier         7394
ex_fan             7394
dtype: int64

In [48]:
len(df_resampled)

8769