In [19]:
import pandas as pd

# read csv file 

df = pd.read_csv('/Users/nannam/Downloads/dash_project/hydroponics_data.csv')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50570 entries, 0 to 50569
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               50570 non-null  int64
 1   timestamp        50570 non-null  str
 2   pH               50570 non-null  float64
 3   TDS              50570 non-null  float64
 4   water_level      50570 non-null  int64
 5   DHT_temp         50570 non-null  float64
 6   DHT_humidity     50570 non-null  float64
 7   water_temp       50570 non-null  float64
 8   pH_reducer       50570 non-null  str
 9   add_water        50566 non-null  str
 10  nutrients_adder  50570 non-null  str
 11  humidifier       50570 non-null  str
 12  ex_fan           50570 non-null  str
dtypes: float64(5), int64(2), str(6)
memory usage: 5.0 MB

In [4]:
df.describe()

,id,pH,TDS,water_level,DHT_temp,DHT_humidity,water_temp
count,50570.000000,50570.000000,50570.000000,50570.000000,50570.000000,50570.000000,50570.000000
mean,25285.500000,6.001514,1154.134377,1.258829,24.316781,71.714188,21.494904
std,14598.445893,0.553016,247.507196,0.479218,1.209319,25.956493,2.174898
min,1.000000,0.270000,-283.910000,0.000000,12.300000,25.000000,0.000000
25%,12643.250000,5.630000,1020.040000,1.000000,23.600000,67.500000,19.770000
50%,25285.500000,5.790000,1234.650000,1.000000,24.400000,71.700000,21.520000
75%,37927.750000,6.680000,1329.067500,2.000000,25.100000,77.500000,23.277500
max,50570.000000,11.570000,2278.350000,3.000000,70.000000,3312.600000,25.000000

In [5]:
# check missing value

df.isnull().sum()

id                 0
timestamp          0
pH                 0
TDS                0
water_level        0
DHT_temp           0
DHT_humidity       0
water_temp         0
pH_reducer         0
add_water          4
nutrients_adder    0
humidifier         0
ex_fan             0
dtype: int64

In [6]:
# check same rows 

df.duplicated().sum()

np.int64(0)

In [15]:
# choose 3 important columns

df_subset = df[['id','timestamp','pH', 'TDS', 'water_temp']]

df_subset.head()

   id            timestamp   pH    TDS  water_temp
0   1  2023-11-26 10:57:52  7.0  500.0        20.0
1   2  2023-11-26 10:58:37  7.0  500.0        20.0
2   3  2023-11-26 11:01:34  7.0  500.0        20.0
3   4  2023-12-05 11:30:58  7.0  500.0        20.0
4   5  2023-12-05 11:33:50  7.0  500.0        20.0

In [16]:
df_subset.isnull().sum()

id            0
timestamp     0
pH            0
TDS           0
water_temp    0
dtype: int64

In [17]:
df_subset.duplicated().sum()

np.int64(0)

In [21]:
df_subset.to_csv('hydro_clean_data.csv', index=False)